[env:blackpill_f401ce]
platform         = ststm32
board            = blackpill_f401ce
framework        = arduino

; Flash via USB DFU bootloader — no ST-Link programmer needed
upload_protocol  = dfu

; Serial monitor speed — must match Serial.begin() in main.cpp
monitor_speed    = 115200

build_flags =
    -lm                                      ; math library for sqrtf, atan2f
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC      ; enable USB CDC serial port